version: "3"

tasks:
############################################################################
#  Darwin related commands
############################################################################
  build:
    desc: "First pass build to get everything downloaded and setup"
    cmds:
    - nix run nix-darwin --extra-experimental-features nix-command --extra-experimental-features flakes -- switch --flake ~/.config/nix --impure
  
  rebuild:
    desc: "Rebuild the environment for a specific host (defaults to current hostname)"
    vars:
      HOSTNAME:
        sh: '{{if .CLI_ARGS}}echo {{.CLI_ARGS}}{{else}}scutil --get LocalHostName{{end}}'
    cmds:
    - echo "Rebuilding for host {{.HOSTNAME}}"
    - sudo darwin-rebuild switch --flake ~/.config/nix#{{.HOSTNAME}} --impure

  darwin-debug:
    desc: "For initial debugging of the build"
    vars:
      HOSTNAME:
        sh: scutil --get LocalHostName
    cmds:
    - nix build .#darwinConfigurations.{{HOSTNAME}}.system --show-trace --verbose --extra-experimental-features 'nix-command flakes'
    - ./result/sw/bin/darwin-rebuild switch --flake .#{{HOSTNAME}} --show-trace --verbose

############################################################################
#  nix related commands
############################################################################
  update:
    desc: "update flake lock file"
    cmds:
    - nix flake update --extra-experimental-features nix-command --extra-experimental-features flakes

  history:
    desc: "View nix system history"
    cmds:
    - nix profile history --profile /nix/var/nix/profiles/system

  garbage:
    desc: "Remove generations older than 7 days and collect unused nix store entries"
    cmds:
      # remove all generations older than 7 days
      - sudo nix profile wipe-history --profile /nix/var/nix/profiles/system  --older-than 7d
      # garbage collect all unused nix store entries
      - sudo nix store gc --debug

  fmt:
    desc: "Format all nix files in repo"
    cmds:
      - nix fmt .

  clean:
    desc: "Removes ./reuslt folder"
    cmds:
      - rm -rf result
