onboarding = false

[theme]
name = "catppuccin"
auto_switch = false

[ui]
agent_panel_sort = "spaces"
show_agent_labels_on_pane_borders = true

[ui.toast]
delivery = "herdr"

[ui.sound]
enabled = true

[keys]
prefix = "ctrl+g"
switch_workspace = "alt+1..9"
focus_pane_left = ["prefix+h", "alt+h"]
focus_pane_down = ["prefix+j", "alt+j"]
focus_pane_up = ["prefix+k", "alt+k"]
focus_pane_right = ["prefix+l", "alt+l"]
new_tab = ["prefix+c", "alt+n"]
next_tab = ["prefix+n", "alt+]"]
previous_tab = ["prefix+p", "alt+["]
split_vertical= ["prefix+v", "alt+v"]
split_horizontal= ["prefix+minus", "alt+minus"]

[terminal]
default_shell = "fish"
