# Generated by scripts/update-omp-release.sh. Do not edit by hand.
{
  tag = "v18.0.9";
  assets = {
    aarch64-darwin = {
      name = "omp-darwin-arm64";
      hash = "sha256-AcAoyJrFmiZ9+BagEz35y9hDIxeYoBd2V3GUaMy8MEU=";
    };
    x86_64-darwin = {
      name = "omp-darwin-x64";
      hash = "sha256-hWvw69IAX1ZANEdBBblW/QrwPdGVF8pAmcc4d09WRA4=";
    };
  };
}
