#!/usr/bin/env bash
# Update the Nix-pinned OMP binary to GitHub's latest stable release.
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

for command in gh git jq nix; do
  command -v "$command" >/dev/null || {
    echo "error: required command not found: $command" >&2
    exit 1
  }
done

release="$(gh api repos/can1357/oh-my-pi/releases/latest)"
tag="$(jq --raw-output '.tag_name' <<<"$release")"
if [[ ! "$tag" =~ ^v[0-9]+(\.[0-9]+){2}([-.][0-9A-Za-z.-]+)?$ ]]; then
  echo "error: GitHub returned an unexpected OMP release tag: $tag" >&2
  exit 1
fi

asset_hash() {
  local name="$1"
  local digest

  digest="$(jq --raw-output --arg name "$name" '
    [.assets[] | select(.name == $name) | .digest] | if length == 1 then .[0] else empty end
  ' <<<"$release")"
  if [[ ! "$digest" =~ ^sha256:[0-9a-f]{64}$ ]]; then
    echo "error: release $tag has no valid SHA-256 digest for $name" >&2
    exit 1
  fi

  nix hash convert --hash-algo sha256 --to sri "$digest"
}

arm64_hash="$(asset_hash omp-darwin-arm64)"
x64_hash="$(asset_hash omp-darwin-x64)"

release_file="modules/home-manager/programs/omp-release.nix"
tmp_release="$(mktemp "${release_file}.XXXXXX")"
trap 'rm -f "$tmp_release"' EXIT

cat >"$tmp_release" <<EOF
# Generated by scripts/update-omp-release.sh. Do not edit by hand.
{
  tag = "$tag";
  assets = {
    aarch64-darwin = {
      name = "omp-darwin-arm64";
      hash = "$arm64_hash";
    };
    x86_64-darwin = {
      name = "omp-darwin-x64";
      hash = "$x64_hash";
    };
  };
}
EOF
mv "$tmp_release" "$release_file"
trap - EXIT

echo "OMP is pinned to $tag. Rebuild with: task rebuild"
